version: '3.6'
services:

  celery-worker:
    image: wes-elixir:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    links:
      - rabbit
    command: bash -c "cd /app/wes_elixir; celery worker -A celery_worker -E --loglevel=info"
    volumes:
      - ../data:/data
      - /wes/vol:/tmp

  wes-elixir:
    image: wes-elixir:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    links:
      - mongo
    command: bash -c "cd /app/; python wes_elixir/app.py"
    volumes:
      - ../data:/data

  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    links:
      - mongo

  mongo:
    image: mongo:3.2
    restart: always
    volumes:
      - ../data/db:/data/db
