# General server/service settings

# Security settings
security:
    authorization_required: True

# Database settings
database:
    host: 'mongo-wes-elixir'
    name: wes-elixir-db-dev

# Storage
storage:
    permanent_dir: '/data/output'
    tmp_dir: '/data/tmp'

# Celery task queue
celery:
    broker_host: 'rabbit-wes-elixir'

# OpenAPI specs

# WES service info settings

# TES server
